#!/bin/bash
set -e

if git diff --cached --quiet; then
  echo "No staged changes found."
  exit 0
fi

npm run format -- --ui=stream
npm run lint -- --ui=stream
npm test -- --ui=stream

git update-index --again
