#!/bin/bash
set -e

if git diff --cached --quiet; then
  echo "No staged changes found."
  exit 0
fi

if git diff --name-only | grep -qx "package-lock.json"; then
  echo "❌ ERROR: Detected changes to package-lock.json that are not committed. Please add and commit the lockfile before proceeding."
  exit 1
fi

npm run build -- --ui=stream
npm run format -- -- --ui=stream
npm run lint -- -- --ui=stream
npm test -- --ui=stream

git update-index --again
